In [1]:
import numpy as np

In [2]:
a = np.array(([1,2,3], [4,5,6]))

In [3]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
np.squeeze(a)

array([[1, 2, 3],
       [4, 5, 6]])

In [24]:
A = np.random.randn(4,3) * 1000
A

array([[ -493.11531156, -2394.28272396,   762.80551674],
       [  821.99067413,  -649.61865934,   483.24568122],
       [   31.08647324,   451.33833734,   782.42737982],
       [   -3.35624547, -2886.1790977 ,   461.30634864]])

In [25]:
B = np.sum(A, axis=1, keepdims=True)
B

array([[-2124.59251878],
       [  655.61769602],
       [ 1264.8521904 ],
       [-2428.22899453]])

In [15]:
B.shape

(4, 1)

In [26]:
np.tanh(A)

array([[-1.        , -1.        ,  1.        ],
       [ 1.        , -1.        ,  1.        ],
       [ 1.        ,  1.        ,  1.        ],
       [-0.99757169, -1.        ,  1.        ]])